### ISSUE TITLE
Upgrade meshkit errors

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshery-consul#162] opened 2021-06-16 17:08 UTC
**Current Behavior**
Port meshkit errors to the new error utility function. Instructions covered in layer5io/meshkit#48
---
**Resources**

**Alternatives / Additional Context**

**Comment by mgfeller** [comment] 2021-06-24 18:03
duplicate of #163

**Closed by mgfeller** 2021-06-24 18:03 UTC
Labels: kind/enhancement
