### ISSUE TITLE
[CI] Incorporate the running of the BATS integration tests in the CI workflow

### ISSUE THREAD

**Issue by mgfeller** [layer5io/meshery-consul#133] opened 2020-12-24 13:16 UTC
**Current Behavior**

Currently, BATS tests can only be run locally, they're not executed as part of the CI-workflow.

**Desired Behavior**

BATS integration tests should be executed as part of  GitHub CI-workflow.

---
**Resources**

* Creating cluster using KinD: https://github.com/layer5io/meshery-linkerd/blob/master/.github/workflows/ci.yml
* There exists a github action that could be used: https://github.com/marketplace/actions/setup-bats-testing-framework
* BATS version used in consul is https://github.com/bats-core/bats-core (https://github.com/sstephenson/bats isn't maintained anymore)

**Alternatives / Additional Context**

* The tests are run directly against the adapter.
* Locally, the tests can be run by `make e2e-tests-localhost` if the adapter is reachable on localhost
* If not, the the env variable `MESHERY_ADAPTER_ADDR` can be set, and `make e2e-tests` used to run the tests.

**Comment by ramrodo** [comment] 2020-12-24 17:43
@mgfeller I just working on creating a cluster using KinD in [PR#2139](https://github.com/layer5io/meshery/pull/2139). Once this is merged, we can continue to add the BATS Github Action

**Comment by mgfeller** [comment] 2020-12-26 12:07
@ramrodo looking forward to that! Just to avoid misunderstandings, this issue is about extending the CI workflow in this repository, not `meshery`.

**Comment by ramrodo** [comment] 2020-12-26 18:13
Thanks for the clarification @mgfeller, I was confused. So, we'll start working on that with this project.

**Comment by ramrodo** [comment] 2021-01-15 00:26
Hey @mgfeller, I'm executing the e2e tests but they stop at:

```bash
   daemonset/consul-consul should be ready                                              13/38
```

because of this test:

```
$ kubectl rollout status daemonset/consul-consul -n consul-e2e-tests
Waiting for daemon set "consul-consul" rollout to finish: 0 of 1 updated pods are available...
```

Have you faced this error on that test before?

Also, if you execute that test on your computer today, does it pass? And if it does, can we have a meet to check that, please?

**Comment by mgfeller** [comment] 2021-01-15 17:08
Hey @ramrodo 

No, I don't think I've faced this error before, and not today.
I'm running in-process and use minikube.

Yes, of course we can have a meeting.

**Comment by ramrodo** [comment] 2021-01-15 17:31
Ok @mgfeller. I'm using KinD for the k8s cluster. Maybe the problem is about the capacity of the cluster. How many master and worker nodes do you have in your minikube cluster? Also, what are the resources/limits of each one in CPU and memory?

**Comment by mgfeller** [comment] 2021-01-15 18:44
@ramrodo yes that is possible. `minikube --memory 8192 --cpus 4 start -p meshery2`, just one node on my PC, which has 8 cpu and 32 GB RAM, not quite sure whether minikube honors the start parameter as kubectl reports the capacity of the PC.

**Comment by ramrodo** [comment] 2021-01-18 21:29
@mgfeller I found the root cause. I was deploying `HTTPbin` and other applications before running the e2e tests. I didn't know that those tests will create them also. 

Now I'm facing errors when the e2e tests deploy `bookinfo` app:

```
{"app":"consul-adapter","level":"info","message":"installing Istio Book Info Application","ts":"2021-01-18T15:16:02.604985311-06:00"}
600 Error
{"app":"consul-adapter","level":"info","message":"removing Istio Book Info Application","ts":"2021-01-18T15:17:44.809864239-06:00"}
600 Error
```

- Have you seen that `600 Error` before?
- Do I need to configure Istio to be able to deploy that "Istio Book Info" app?

**Comment by ramrodo** [comment] 2021-01-18 23:59
@mgfeller NVM, I downloaded the latest changes from this repository and re-kicked the tests in localhost. Now, the tests pass.

**Comment by mgfeller** [comment] 2021-01-19 07:41
@ramrodo excellent. I usually run on a pristine kubernetes cluster, to have a well defined and known starting point. apart from that, there are no prerequisites in the cluster. 
I've had 600 Errors before, unfortunately, they're just general panic errors that need to be troubleshooted / debugged.

**Closed** 2021-01-20 16:28 UTC
Labels: area/ci, area/tests, kind/enhancement
